apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 476ac9e8b4c024b46d1b7be094734737f6b18a41
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 1995335eb05b3ca01789b007435d9b3be736ec4f
